version: '2'
services:
  web:
    build: ./images/nginx
    ports:
      - '10080:80'
      - '443:443'
    depends_on:
      - app
    volumes_from:
      - app
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    restart: always

  app:
    build: ./images/app
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html
    restart: always

  db:
    image: mysql:5.7
    volumes:
      - wp_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  wp_db_data: {}